language: ruby
addons:
  postgresql: "9.4"
rvm:
 - "2.2.1"
cache: bundler
bundler_args: --without production development
before_install:
  - gem install bundler
before_script:
  - "for i in config/*.example; do cp \"$i\" \"${i/.example}\"; done"
  - bundle exec rake db:drop db:create db:migrate
script:
  - RAILS_ENV=test bundle exec rake assets:precompile
  - RAILS_ENV=test bundle exec rake sunspot:solr:start
  - RAILS_ENV=test bundle exec rspec spec
  - RAILS_ENV=test bundle exec rake sunspot:solr:stop